In [10]:
#Q (a)
def store_tri_ang(a):
    n=len(a)  
    u=[]
    #i=0
    for j in range(n): 
        for k in range(j+1): 
            u.append(a[j][k])
    return u
def retrieve_tri_ang(u,m):
    n=len(m)
    a=[[0]*n for _ in range(n)]
    for j in range(n):
        for k in range(n):
            if k>j:
                a[j][k]=0
            else:
                l=(j*(j+1))//2+k
                a[j][k]=u[l]
    return a
a=[[4,0,0,0],[3,5,0,0],[1,6,2,0],[8,0,5,9]]
u=store_trg(a)
print('store triangular: ',u)
r=retrieve_trg(u,a)
print('retrieve triangular: ',r)

store triangular:  [4, 3, 5, 1, 6, 2, 8, 0, 5, 9]
retrieve triangular:  [[4, 0, 0, 0], [3, 5, 0, 0], [1, 6, 2, 0], [8, 0, 5, 9]]


##Q(c)
1. Size of U :

A tridiagonal matrix has non-zero elements only on:
main diagonal → n elements
upper diagonal → n-1 elements
lower diagonal → n-1 elements
So, total size of U = n + (n-1) + (n-1) = 3n – 2

2. Index L if U[L] = B[J][K]:

Each row j (0-based) can have up to 3 elements: (j, j-1), (j, j), (j, j+1)
To find position L, count elements stored before row j, then add offset inside row j.
L = 2j + k
where:
if k == j-1 → lower diagonal element
if k == j → main diagonal element
if k == j+1 → upper diagonal element

In [17]:
#Q (d)
def store_tri_dig(b):
    n=len(b)
    u=[]
    for j in range(n):
        for k in range(n):
            if b[j][k]!=0:
                u.append(b[j][k])
    return u
#Q (e)
def retrieve_tri_dig(u,m):
    n=len(m)
    b=[[0]*n for _ in range(n)]
    i=0
    for j in range(n):
        for k in range(n):
            if abs(j-k)<=1:
                b[j][k]=u[i]
                i+=1
    return b
b=[[5,-7,0,0],[1,4,3,0],[0,9,-3,6],[0,0,2,4]]
u=store_tri_dig(b)
print('store tridigonal:',u)
r=retrieve_tri_dig(u,b)
print('retrieve tridigonal:',r)

store tridigonal: [5, -7, 1, 4, 3, 9, -3, 6, 2, 4]
retrieve tridigonal: [[5, -7, 0, 0], [1, 4, 3, 0], [0, 9, -3, 6], [0, 0, 2, 4]]


In [26]:
#q (f)
import numpy as np
from scipy.sparse import csr_matrix
dense_matrix = np.array([
    [1, 0, 0, 0, 2, 0],
    [0, 0, 3, 0, 0, 4],
    [5, 0, 0, 6, 0, 0]
])
print("Original Dense Matrix:\n", dense_matrix)

sparse_csr = csr_matrix(dense_matrix)
print("CSR Sparse Matrix Representation:\n", sparse_csr)
print("Data (non-zero values):", sparse_csr.data)

back_to_dense = sparse_csr.toarray()
print("Converted Back to Dense Matrix:\n",back_to_dense)

Original Dense Matrix:
 [[1 0 0 0 2 0]
 [0 0 3 0 0 4]
 [5 0 0 6 0 0]]
CSR Sparse Matrix Representation:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (3, 6)>
  Coords	Values
  (0, 0)	1
  (0, 4)	2
  (1, 2)	3
  (1, 5)	4
  (2, 0)	5
  (2, 3)	6
Data (non-zero values): [1 2 3 4 5 6]
Converted Back to Dense Matrix:
 [[1 0 0 0 2 0]
 [0 0 3 0 0 4]
 [5 0 0 6 0 0]]
